# Generated by Django 5.2.9 on 2026-01-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_image_url_productimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='attribute',
            new_name='attributes',
        ),
    ]
